# Use latest Node LTS to build
FROM node:lts AS builder

# Copy Vue.js code
WORKDIR /app
COPY webui webui

# Build Vue.js into plain HTML/CSS/JS
WORKDIR /app/webui
RUN npm run build-prod

# Create final container
FROM nginx:1.23.1

# OTEL autoinstrumentation for NGINX
RUN apt-get update ; apt-get install unzip
ADD https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases/download/webserver%2Fv1.0.3/opentelemetry-webserver-sdk-x64-linux.tgz /opt
RUN cd /opt ; unzip opentelemetry-webserver-sdk-x64-linux.tgz.zip; tar xvfz opentelemetry-webserver-sdk-x64-linux.tgz
RUN cd /opt/opentelemetry-webserver-sdk; ./install.sh
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/opentelemetry-webserver-sdk/sdk_lib/lib
RUN echo "load_module /opt/opentelemetry-webserver-sdk/WebServerModule/Nginx/1.23.1/ngx_http_opentelemetry_module.so;\n$(cat /etc/nginx/nginx.conf)" > /etc/nginx/nginx.conf
COPY opentelemetry_module.conf /etc/nginx/conf.d

# Copy the (built) app from the builder image
COPY --from=builder /app/webui/dist /usr/share/nginx/html
