services:
  backend:
    image: docker.io/aleiis/wasaphoto-backend:v1.3
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - WASAPHOTO_CONFIG_FILE=/app/config.yml
    volumes:
      - ./config.yml:/app/config.yml
      - wasaphoto-data:/app/wasaphoto
  frontend:
    image: docker.io/aleiis/wasaphoto-frontend:v1.1
    container_name: frontend
    ports:
      - "8080:80"

volumes:
  wasaphoto-data: