# Use latest Node LTS to build
FROM node:lts AS builder

# Copy Vue.js code
WORKDIR /app
COPY webui webui

# Update dependencies
WORKDIR /app/webui
RUN rm -f webui/package-lock.json
RUN rm -rf webui/node_modules
RUN npm i

# Build Vue.js into plain HTML/CSS/JS
RUN npm run build

# Create final container
FROM nginx:stable

# Copy the (built) app from the builder image
COPY --from=builder /app/webui/dist /usr/share/nginx/html
