# This is the configuration file for the API service
# Description of this part is present in the `main.go` file

# If a log file is not provided, stdout will be used
# Folders will be created if they do not exist

config_file: "config.yml"
log_file: "/wasaphoto/log/webapi.log"
debug: false
db:
  filename: "/wasaphoto/data/wasaphoto.db"
  log_file: "/wasaphoto/log/db.log"
web:
  api_host: "0.0.0.0:3000"
  debug_host: "0.0.0.0:4000"
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 5s
