# This is the configuration file for the API service
# Description of this part is present in the `main.go` file

db:
  filename: wasaphoto.db
debug: false
web:
  apihost: 0.0.0.0:3000
  debughost: 0.0.0.0:4000
  readtimeout: 5s
  writetimeout: 5s
  shutdowntimeout: 5s
